# Force OS X.
language: objective-c

os: osx

env: OSX=10.11
osx_image: xcode7.3

matrix:
  include:
    - env: OSX=10.11
      osx_image: xcode8

notifications:
  email: false

script:
  - ./script/cibuild
