# Force OS X.
language: objective-c
os: osx
env: OSX=10.11
osx_image: osx10.11
matrix:
  include:
    - env: OSX=10.10
      osx_image: xcode7
    - env: OSX=10.9
      osx_image: beta-xcode6.2

notifications:
  email: false

script:
  - ./script/cibuild
