# Force OS X.
language: objective-c
os: osx
matrix:
  include:
    - env: OSX=10.11
      osx_image: xcode8
    - env: OSX=10.11
      osx_image: xcode7.3

notifications:
  email: false

script:
  - ./script/cibuild
